language: go

go:
  - tip

script:
  # Move from github.com to gopkg.in directory
  - mkdir -p "$GOPATH/src/gopkg.in/pd93"
  - mv "$TRAVIS_BUILD_DIR" "$GOPATH/src/gopkg.in/pd93"
  - cd "$GOPATH/src/gopkg.in/pd93/plog"
  - make codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)
